#yml具有多文档模式
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: test
---
server:
  port: 8083
spring:
  profiles:
    active: dev
  messages:
    basename: i18n.login #配置文件的真实路径
  thymeleaf:
    cache: false